//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smart-home.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public enum BrewResult implements java.io.Serializable
{
    Ready(0),
    NoBeans(1),
    NoWater(2),
    NoMilk(3),
    NoFilters(4),
    GroundsFull(5);

    public int value()
    {
        return _value;
    }

    public static BrewResult valueOf(int v)
    {
        switch(v)
        {
        case 0:
            return Ready;
        case 1:
            return NoBeans;
        case 2:
            return NoWater;
        case 3:
            return NoMilk;
        case 4:
            return NoFilters;
        case 5:
            return GroundsFull;
        }
        return null;
    }

    private BrewResult(int v)
    {
        _value = v;
    }

    public void ice_write(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeEnum(_value, 5);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, BrewResult v)
    {
        if(v == null)
        {
            ostr.writeEnum(SmartHome.BrewResult.Ready.value(), 5);
        }
        else
        {
            ostr.writeEnum(v.value(), 5);
        }
    }

    public static BrewResult ice_read(com.zeroc.Ice.InputStream istr)
    {
        int v = istr.readEnum(5);
        return validate(v);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<BrewResult> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, BrewResult v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            ice_write(ostr, v);
        }
    }

    public static java.util.Optional<BrewResult> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            return java.util.Optional.of(ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static BrewResult validate(int v)
    {
        final BrewResult e = valueOf(v);
        if(e == null)
        {
            throw new com.zeroc.Ice.MarshalException("enumerator value " + v + " is out of range");
        }
        return e;
    }

    private final int _value;
}
