//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smart-home.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class Espresso extends com.zeroc.Ice.Value
{
    public Espresso()
    {
        this.waterUsage = 4;
        this.beansUsage = 4;
        this.filtersUsage = 0;
        this.milkUsage = 0;
        this.groundsProduced = 1;
    }

    public Espresso(int waterUsage, int beansUsage, int filtersUsage, int milkUsage, int groundsProduced)
    {
        this.waterUsage = waterUsage;
        this.beansUsage = beansUsage;
        this.filtersUsage = filtersUsage;
        this.milkUsage = milkUsage;
        this.groundsProduced = groundsProduced;
    }

    public int waterUsage;

    public int beansUsage;

    public int filtersUsage;

    public int milkUsage;

    public int groundsProduced;

    public Espresso clone()
    {
        return (Espresso)super.clone();
    }

    public static String ice_staticId()
    {
        return "::SmartHome::Espresso";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -1516269880L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeInt(waterUsage);
        ostr_.writeInt(beansUsage);
        ostr_.writeInt(filtersUsage);
        ostr_.writeInt(milkUsage);
        ostr_.writeInt(groundsProduced);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        waterUsage = istr_.readInt();
        beansUsage = istr_.readInt();
        filtersUsage = istr_.readInt();
        milkUsage = istr_.readInt();
        groundsProduced = istr_.readInt();
        istr_.endSlice();
    }
}
