//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smart-home.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public interface EspressoCoffeeMachinePrx extends CoffeeMachinePrx
{
    default BrewResult prepareLatte()
    {
        return prepareLatte(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default BrewResult prepareLatte(java.util.Map<String, String> context)
    {
        return _iceI_prepareLatteAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<BrewResult> prepareLatteAsync()
    {
        return _iceI_prepareLatteAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<BrewResult> prepareLatteAsync(java.util.Map<String, String> context)
    {
        return _iceI_prepareLatteAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<BrewResult> _iceI_prepareLatteAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<BrewResult> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "prepareLatte", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     BrewResult ret;
                     ret = BrewResult.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default BrewResult prepareEspresso()
    {
        return prepareEspresso(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default BrewResult prepareEspresso(java.util.Map<String, String> context)
    {
        return _iceI_prepareEspressoAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<BrewResult> prepareEspressoAsync()
    {
        return _iceI_prepareEspressoAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<BrewResult> prepareEspressoAsync(java.util.Map<String, String> context)
    {
        return _iceI_prepareEspressoAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<BrewResult> _iceI_prepareEspressoAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<BrewResult> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "prepareEspresso", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     BrewResult ret;
                     ret = BrewResult.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default double getRemainingMilkPercentage()
    {
        return getRemainingMilkPercentage(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default double getRemainingMilkPercentage(java.util.Map<String, String> context)
    {
        return _iceI_getRemainingMilkPercentageAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> getRemainingMilkPercentageAsync()
    {
        return _iceI_getRemainingMilkPercentageAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> getRemainingMilkPercentageAsync(java.util.Map<String, String> context)
    {
        return _iceI_getRemainingMilkPercentageAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> _iceI_getRemainingMilkPercentageAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getRemainingMilkPercentage", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     double ret;
                     ret = istr.readDouble();
                     return ret;
                 });
        return f;
    }

    default void refillMilk()
    {
        refillMilk(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void refillMilk(java.util.Map<String, String> context)
    {
        _iceI_refillMilkAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> refillMilkAsync()
    {
        return _iceI_refillMilkAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> refillMilkAsync(java.util.Map<String, String> context)
    {
        return _iceI_refillMilkAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_refillMilkAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "refillMilk", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static EspressoCoffeeMachinePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), EspressoCoffeeMachinePrx.class, _EspressoCoffeeMachinePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static EspressoCoffeeMachinePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), EspressoCoffeeMachinePrx.class, _EspressoCoffeeMachinePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static EspressoCoffeeMachinePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), EspressoCoffeeMachinePrx.class, _EspressoCoffeeMachinePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static EspressoCoffeeMachinePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), EspressoCoffeeMachinePrx.class, _EspressoCoffeeMachinePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static EspressoCoffeeMachinePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, EspressoCoffeeMachinePrx.class, _EspressoCoffeeMachinePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static EspressoCoffeeMachinePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, EspressoCoffeeMachinePrx.class, _EspressoCoffeeMachinePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (EspressoCoffeeMachinePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_adapterId(String newAdapterId)
    {
        return (EspressoCoffeeMachinePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (EspressoCoffeeMachinePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (EspressoCoffeeMachinePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_invocationTimeout(int newTimeout)
    {
        return (EspressoCoffeeMachinePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_connectionCached(boolean newCache)
    {
        return (EspressoCoffeeMachinePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (EspressoCoffeeMachinePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_secure(boolean b)
    {
        return (EspressoCoffeeMachinePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (EspressoCoffeeMachinePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_preferSecure(boolean b)
    {
        return (EspressoCoffeeMachinePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (EspressoCoffeeMachinePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (EspressoCoffeeMachinePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_collocationOptimized(boolean b)
    {
        return (EspressoCoffeeMachinePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_twoway()
    {
        return (EspressoCoffeeMachinePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_oneway()
    {
        return (EspressoCoffeeMachinePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_batchOneway()
    {
        return (EspressoCoffeeMachinePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_datagram()
    {
        return (EspressoCoffeeMachinePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_batchDatagram()
    {
        return (EspressoCoffeeMachinePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_compress(boolean co)
    {
        return (EspressoCoffeeMachinePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_timeout(int t)
    {
        return (EspressoCoffeeMachinePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_connectionId(String connectionId)
    {
        return (EspressoCoffeeMachinePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default EspressoCoffeeMachinePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (EspressoCoffeeMachinePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SmartHome::EspressoCoffeeMachine";
    }
}
