//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smart-home.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

/** @hidden */
public class _ThermometerPrxI extends com.zeroc.Ice._ObjectPrxI implements ThermometerPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
