//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smart-home.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class Americano extends com.zeroc.Ice.Value
{
    public Americano()
    {
        this.waterUsage = 11;
        this.beansUsage = 3;
        this.filtersUsage = 1;
        this.milkUsage = 0;
        this.groundsProduced = 2;
    }

    public Americano(int waterUsage, int beansUsage, int filtersUsage, int milkUsage, int groundsProduced)
    {
        this.waterUsage = waterUsage;
        this.beansUsage = beansUsage;
        this.filtersUsage = filtersUsage;
        this.milkUsage = milkUsage;
        this.groundsProduced = groundsProduced;
    }

    public int waterUsage;

    public int beansUsage;

    public int filtersUsage;

    public int milkUsage;

    public int groundsProduced;

    public Americano clone()
    {
        return (Americano)super.clone();
    }

    public static String ice_staticId()
    {
        return "::SmartHome::Americano";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -20208121L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeInt(waterUsage);
        ostr_.writeInt(beansUsage);
        ostr_.writeInt(filtersUsage);
        ostr_.writeInt(milkUsage);
        ostr_.writeInt(groundsProduced);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        waterUsage = istr_.readInt();
        beansUsage = istr_.readInt();
        filtersUsage = istr_.readInt();
        milkUsage = istr_.readInt();
        groundsProduced = istr_.readInt();
        istr_.endSlice();
    }
}
